# Generated by Django 5.1.7 on 2025-03-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScammersList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporters_name", models.CharField(blank=True, max_length=100)),
                ("reporters_email", models.CharField(blank=True, max_length=100)),
                ("reporter_phone", models.CharField(blank=True, max_length=20)),
                ("scammers_name", models.CharField(blank=True, max_length=100)),
                ("scammers_account", models.CharField(blank=True, max_length=100)),
                ("scammers_bank", models.CharField(blank=True, max_length=100)),
                ("scammers_phone", models.CharField(blank=True, max_length=20)),
                ("scammers_instagram", models.CharField(blank=True, max_length=100)),
                ("scammers_twitter", models.CharField(blank=True, max_length=100)),
                ("date_occurred", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                (
                    "scammers_image",
                    models.ImageField(blank=True, upload_to="scammers_images"),
                ),
                (
                    "other_documents",
                    models.FileField(blank=True, upload_to="scammers_documents"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Scammer",
                "verbose_name_plural": "Scammers",
                "ordering": ["-date_occurred"],
            },
        ),
    ]
