# Generated by Django 5.1.7 on 2025-03-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scammers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scammerslist",
            name="business_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
