# Generated by Django 5.1.7 on 2025-03-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scammers", "0002_scammerslist_business_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="scammerslist",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
