# Generated by Django 5.1.7 on 2025-03-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scammers", "0003_scammerslist_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scammerslist",
            name="other_documents",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="scammerslist",
            name="scammers_image",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
